---
title: "San Rafael Canal District Parcel Analysis"
author: "Olivia Won"
date: "2023-11-29"
output:
  pdf_document: default
  html_document: default
---

```{r Load Libraries, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(readxl)
library(scales)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

## Overview

This script runs analyses of parcels in the Canal District that will experience varying inundation with 12 inches or 1 foot of sea-level rise.

```{r Read in Data}
#Read in Canal District Parcels inundated with 12" SLR
canalparcels_SLR12 <- read_csv(here("data", "Canal_District_Parcels2023.csv"))
canalparcels_SLR12 
sapply(canalparcels_SLR12, class)
canalparcels_SLR12 <- transform(canalparcels_SLR12,
                           Land_Assessed_Value_TY2023 = as.numeric(as.factor(Land_Assessed_Value_TY2023)),
                           Improvements_Assessed_Value_TY2023 = as.numeric(as.factor(Improvements_Assessed_Value_TY2023)),
                           Personal_Assessed_Value_TY2023 = as.numeric(as.factor(Personal_Assessed_Value_TY2023)),
                           Total_Assessed_Value_TY2023 = as.numeric(as.factor(Total_Assessed_Value_TY2023)))

#Tidy dataframe
canalparcels_SLR12<-canalparcels_SLR12 %>% 
  select(Parcel, Prop_ID, MAX_gridcode, Deed_ReferenceID, Owner_Name, Tax_Rate_Area, Assessment_City,
         Land_Assessed_Value_TY2023, Improvements_Assessed_Value_TY2023, Business_Assessed_Value_TY2023,
         Personal_Assessed_Value_TY2023, Total_Assessed_Value_TY2023, Use_Code, Use_Code_Description,
         Use_Type, Improvement_Status, Living_Units, Construction_Year, Construction_Years, Land_Area_SqFt, 
         Living_Area_SqFt, Bedrooms, Bathrooms, Garage_SqFt, DeckPatio_SqFt, Pool_SqFt, Unfinished_SqFt)
canalparcels_SLR12<- canalparcels_SLR12 %>% 
  filter(!Parcel %in% c("00809307", "00809306", "00916119"))
canalparcels_SLR12[is.na(canalparcels_SLR12)] = 0 

#Exclude non-Canal parcels
canalparcels_SLR12<- canalparcels_SLR12 %>% 
  filter(!MAX_gridcode %in% c(4,5))

#Convert grid code classes to flood depth intervals (in)
canalparcels_SLR12 <- mutate(canalparcels_SLR12, Flooding_Depth_in = case_when(MAX_gridcode == 1 ~ '0 - 2.74'
                                                                       ,MAX_gridcode == 2 ~ '2.74 - 5.48'
                                                                       ,MAX_gridcode == 3 ~ '5.48 - 8.22'))

#Read in Overtopped Parcels
overtopping_parcels_canaldist <- read_csv(here("data", "Overtopping_Parcels_CanalDist.csv"))
overtopping_parcels_canaldist <- overtopping_parcels_canaldist %>% 
  distinct(Prop_ID, FREQUENCY, MAX_gridcode, Overtopped)
overtopping_parcels_canaldist <- overtopping_parcels_canaldist %>% 
  filter(Overtopped == "Overtopped") %>%  
  select(c(Prop_ID, Overtopped))


```


## Summary Plots

The following plots provide summary information about parcels impacted in the Canal District with 12" SLR

```{r Summary Plots, echo=TRUE}
#Summary: Impacted parcels by flooding depth, use type, and total assessed value
summary_canalparcels_SLR12_flooddepth <- canalparcels_SLR12 %>%
  group_by(Flooding_Depth_in, Use_Type)%>%
  summarise(Total_Assessed_Value_sum = sum(Total_Assessed_Value_TY2023)) %>%
  ungroup()
summary_canalparcels_SLR12_flooddepth <- summary_canalparcels_SLR12_flooddepth %>% 
  filter(!Use_Type == "Common Area")

ggplot(summary_canalparcels_SLR12_flooddepth, aes(x= Flooding_Depth_in, y= Total_Assessed_Value_sum, 
                                         fill= Use_Type))+ 
  geom_bar(stat= "identity", position=position_dodge())+
  xlab("Flooding Depth (in)")+
  ylab("Total Assessed Value (Tax Year 2023)")+ # Set axis labels
  ggtitle('Total Assessed Value of Impacted Parcels by Use Type and Flooding Depth (in) 
12" SLR Scenario - Canal District')+
  theme_bw()+ 
  scale_y_continuous(labels = label_comma())

#Summary: Total assessed value (tax year 2023) by parcel use type
summary_canalparceltypes_value <- canalparcels_SLR12 %>%
  group_by(Use_Type)%>%
  summarise(Total_Assessed_Value_sum = sum(Total_Assessed_Value_TY2023)) %>%
  ungroup()

summary_canalparceltypes_value <- summary_canalparceltypes_value %>% 
  filter(!Use_Type == "Common Area")

ggplot(summary_canalparceltypes_value, aes(x= Use_Type, y= Total_Assessed_Value_sum))+ 
  geom_bar(stat= "identity", position=position_dodge(), fill="cornflowerblue")+
  xlab("Parcel Use Type")+
  ylab("Total Assessed Value (Tax Year 2023)")+ # Set axis labels
  ggtitle('Total Assessed Value of Impacted Parcels by Use Type
12" SLR Scenario - Canal District')+
  theme_bw()+
  scale_y_continuous(labels = label_comma())+
  theme(axis.text.x = element_text(angle=45, vjust=1, hjust=1))


#Summary: Impacted residential parcels
canalparcels_SLR12_residential <- canalparcels_SLR12 %>%
  filter(Use_Type == "Residential") 

ggplot(canalparcels_SLR12_residential, aes(x=Construction_Years))+
  geom_histogram(stat="count", fill = "cornflowerblue")+
  ggtitle('Construction Year of Impacted Residential Parcels
12" SLR Scenario - Canal District')+
  xlab("Construction Year")+
    theme(axis.text.x = element_text(angle=45, vjust=1, hjust=1))

table(canalparcels_SLR12_residential$Construction_Years)

#Summary: Impacted residential parcels by Construction Year (where data was available)
canalparcels_SLR12_residential_year <- canalparcels_SLR12_residential %>%
  filter(!Construction_Year == "No Data")   

canalparcels_SLR12_residential_year <- canalparcels_SLR12_residential_year %>% 
  filter(!Use_Code_Description == "Multiple-Resid. - Improved")   

ggplot(canalparcels_SLR12_residential_year, aes(Construction_Years, Total_Assessed_Value_TY2023, fill=Use_Code_Description))+
  geom_boxplot()+
  scale_y_continuous(labels = label_comma())+
  theme(axis.text.x = element_text(angle=45, vjust=1, hjust=1))+
  facet_wrap(~Use_Code_Description)+
  xlab("Construction Year")+
  ylab("Total Assessed Value (Tax Year 2023)")+ # Set axis labels
  ggtitle('Construction Year and Total Assessed Value of Impacted Single Family/Residential Parcels
12" SLR Scenario - Canal District')

#Summary: Impacted parcels with living units 
living_units_canal_flooddepth <- canalparcels_SLR12 %>% 
  filter(Living_Units>0) %>% 
  group_by(Flooding_Depth_in, Use_Type)%>%
  summarise(count = sum(Living_Units)) %>%
  ungroup()
sum(living_units_canal_flooddepth$count)

ggplot(living_units_canal_flooddepth, aes(x= Use_Type, y= count))+ 
  geom_bar(stat= "identity", position=position_dodge(), fill = "cornflowerblue")+
  xlab("Use Type")+
  ylab("Number of Living Units")+ # Set axis labels
  ggtitle('Impacted Living Units by Parcel Use Type and Flooding Depth (in)
12" SLR Scenario - Canal District')+
  theme(axis.text.x = element_text(angle=45, vjust=1, hjust=1))+
  geom_text(aes(label = count), vjust=.01)+
  facet_wrap(~Flooding_Depth_in)# Set title

#Summary: Impacted parcels with living unites by use code
living_units_canal_use_code <- canalparcels_SLR12 %>% 
  filter(Living_Units>0) %>% 
  group_by(Flooding_Depth_in, Use_Code_Description)%>%
  summarise(count = sum(Living_Units)) %>%
  ungroup()
ggplot(living_units_canal_use_code, aes(x= Flooding_Depth_in, y= count, fill = Use_Code_Description))+ 
  geom_bar(stat= "identity")+
  xlab("Flooding Depth (in)")+
  ylab("Number of Living Units")+ # Set axis labels
  ggtitle('Impacted Living Units by Parcel Use Category and Flooding Depth (in)
12" SLR Scenario - Canal District')+
  theme(axis.text.x = element_text(angle=45, vjust=1, hjust=1))

#Join canal parcel data with with overtopping data
canalparcels_SLR12_overtopping <- canalparcels_SLR12 %>% 
  left_join(overtopping_parcels_canaldist, by= "Prop_ID")

#Summary: Canal parcels with overtopping 
canalparcels_SLR12_overtopping<- canalparcels_SLR12_overtopping %>%
  filter(Overtopped == "Overtopped")

ggplot(canalparcels_SLR12_overtopping, aes(x=Use_Type))+
  geom_histogram(stat="count", fill = "cornflowerblue")+
  ggtitle("Canal District Parcels adjacent to Overtopped Shoreline")+
  theme(axis.text.x = element_text(angle=45, vjust=1, hjust=1))

#Summary: Canal parcels with living units AND overtopping 
living_units_canalparcels_SLR12_overtopping <- canalparcels_SLR12_overtopping %>% 
  filter(Living_Units>0) %>% 
  group_by(Flooding_Depth_in, Use_Code_Description)%>%
  summarise(count = sum(Living_Units)) %>%
  ungroup()

ggplot(living_units_canalparcels_SLR12_overtopping, aes(x= Use_Code_Description, y= count))+ 
  geom_bar(stat= "identity", position=position_dodge(), fill = "cornflowerblue")+
  xlab("Inundation Category")+
  ylab("Living Units")+ # Set axis labels
  ggtitle('Impacted Living Units by Parcel Use Type and Flooding Depth (in) Near Overtopping Points
12" SLR Scenario - Canal District')+
  theme(axis.text.x = element_text(angle=45, vjust=1, hjust=1))+
  geom_text(aes(label = count), vjust=.2)+
  facet_wrap(~Flooding_Depth_in)# Set title```

```